language: go
sudo: required
dist: trusty


go:
    - 1.7

env:
  global:
    - LLVM_VERSION=3.9.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH
  - llvm-config --version
  - llvm-config --includedir
  - llvm-config --libdir
  - export CGO_LDFLAGS="-L`llvm-config --libdir`"
  - echo $CGO_LDFLAGS
